apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.airflow.worker.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: worker
    spec:
      restartPolicy: Always
      containers:
      - name: worker
        image: {{ .Values.airflow.image }}
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: postgres-password
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: postgres-password
        - name: RABBITMQ_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: rabbitmq-password
        - name: AIRFLOW_FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: airflow-fernet-key
        - name: AIRFLOW_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: airflow-secret-key
        - name: SMTP_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: airflow-smtp-password
        args: ["worker"]
        volumeMounts:
          - mountPath: /usr/local/airflow
            name: config
    volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key:  /usr/local/airflow/airflow-conf.sh
            path: $AIRFLOW_HOME/airflow-conf.sh
